config/routes.rb
Rails.application.routes.draw do
  scope 'fetch_event/:event_type' do
    resources :events, except: :show do
      get 'get_events', on: :collection
      post 'move', on: :collection
      post 'resize', on: :collection
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :take_event_constant, only: [:new, :create, :index, :get_events, :move, :resize, :edit, :update, :destroy]

  def new
    if params[:event_click_date].present?
      @event = @event_klass.new(start_time: params[:event_click_date], end_time: (params[:event_click_date].to_date + 5.hour))
    else
      @event = @event_klass.new(end_time: 1.hour.from_now)
    end
    render json: { form: render_to_string( partial: '/events/form') }
  end

  def create
    event_manager = Calendarik::EventSeriesManager::EventSeriesCreator.new(@event_klass, event_params)
    if event_manager.create_event
      render nothing: true
    else
      render text: "Произошла ошибка", status: 422
    end
  end

  def index
  end

  def get_events
    events = @event_klass.where("start_time >= ? and end_time <= ?", params['start'], params['end']).map do |event|
      { 
        id: event.id,
        title: event.title,
        description: event.description,
        start: event.start_time.iso8601,
        end: event.end_time.iso8601,
        freeDay: event.free_day,
        allDay: event.all_day,
        recurring: event.recurring? ? true : false
      }
    end
    render :text => events.to_json
  end

  def move
    event = @event_klass.find_by_id params[:id]
    if event.present?
      time_column_update = Calendarik::WorkWithTime::TimeColumnUpdater.new(event, params)
      time_column_update.process_columns([:start_time, :end_time])
    end
    render nothing: true
  end

  def resize
    event = @event_klass.find_by_id params[:id]
    if event.present?
      time_column_update = Calendarik::WorkWithTime::TimeColumnUpdater.new(event, params)
      time_column_update.process_columns(:end_time)
    end
    render nothing: true
  end

  def edit
    @event = @event_klass.find_by_id(params[:id])
    render json: { form: render_to_string(partial: 'edit_form') }
  end

  def update
    event = @event_klass.find_by_id(params[:id])
    events_updater = Calendarik::EventSeriesManager::EventSeriesUpdater.new(event, event_params)
    events_updater.update_process
    render nothing: true
  end

  def destroy
    event = @event_klass.find_by_id(params[:id])
    if params[:delete_all] == 'true'
      @event_klass.where("id in (?)", event.same_events.map(&:id)).destroy_all
    elsif params[:delete_all] == 'future'
      @event_klass.where("id in (?)", event.future_same_events.map(&:id)).destroy_all
    end
    event.destroy
    render nothing: true
  end

  private

  def event_params
    params.require(params[:event_type]).permit(@event_klass.columns.map(&:name) + [:period, :frequency, :update_format])
  end

  def take_event_constant
    @event_klass = Object.const_get(params[:event_type].camelize)
  end
end

app/views/events/_edit_form.html.erb
<%= form_for @event, url: event_path(id: @event.id), html: { id: 'event_form' } do |f| %>

  <%= render :partial => "shared/events/#{@event_klass.to_s.underscore}_form", :locals => { :f => f }  rescue nil %>

  <p>
    <%= f.label :start_time %>
    <br/>
    <%= f.datetime_select :start_time %>
  </p>
  <p>
    <%= f.label :end_time %>
    <br/>
    <%= f.datetime_select :end_time %>
  </p>
  <p>
    <%= f.label :free_day %>
    <%= f.check_box :free_day %>
  </p>
  <p>
    <% if @event.recurring? %>
      <%= f.select :update_format, options_for_select('Обновить только это событие' => 'update_self', 'Обновить все подобные события' => 'same_events', 'Обновить все будущие события' => 'future_same_events') %>
    <% end -%>

    <%= f.submit %>

    <span id = "updating_events" class="spinner" style = "display:none;">Обновляем, Подождите...</span>
  </p>
<% end %>

app/views/events/_form.html.erb
<%= form_for @event, url: events_path, :html => { :id => 'event_form' } do |f| %>

  <%= render :partial => "shared/events/#{@event_klass.to_s.underscore}_form", :locals => { :f => f } rescue nil %>
  <p>
    <%=f.label :title %>
    <br/>
    <%=f.text_field :title %>
  </p>
  <p>
    <%=f.label :description %>
    <br/>
    <%=f.text_area :description, :rows => 4, :cols => 30 %>
  </p>

  <p>
    <%=f.label :start_time %>
    <br/>
    <%=f.datetime_select :start_time %>
  </p>
  <p>
    <%=f.label :end_time %>
    <br/>
    <%=f.datetime_select :end_time %>
  </p>
  <p>
    <%=f.label :free_day %>
    <%=f.check_box :free_day %>
  </p>
  <p>
    <%=f.label :period %>
    <%=f.select :period, @event_klass.repeat_variants, {}, :onchange => "showPeriodAndFrequency(this.value);" %>
  </p>
  <p id = "frequency" style = "display:none;">
    <%=f.label :frequency %>
    <%=f.select :frequency, (1..30).to_a %> <span id = "period"></span>
  </p>
  <p>
    <%=f.submit %> <span id = "creating_events" class="spinner" style = "display:none;">Создаем событие, Подождите...</span>
  </p>
<% end %>

app/views/events/index.html.erb
<div id="default_link_path" path="/fetch_event/<%= params[:event_type] %>/events"></div>
<p>
  <a href="#" id="new_event">Добавить событие</a>
</p>

<div>
  <div id='calendar'>
  </div>
</div>
<div id = "desc_dialog" class="dialog" style ="display:none;">
  <div id = "event_desc">
  </div>
  <br/>
  <br/>
  <div id = "event_actions">
    <span id = "edit_event"></span>
    <span id = "delete_event"></span>
  </div>
</div>
<div id = "create_event_dialog" class="dialog" style ="display:none;">
  <div id = "create_event">
  </div>
</div>